[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
reka = "AkRsKmDKtdwE6A4fU3M56L5mh1UxspS4MqMCCY4sG1Mg"

[programs.localnet]
reka = "AkRsKmDKtdwE6A4fU3M56L5mh1UxspS4MqMCCY4sG1Mg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
